file(READ "${PLUTOSVG_DIR}/CMakeLists.txt" PLUTOSVG_CMAKELISTS_CONTENTS)
string(REPLACE "export(EXPORT plutosvgTargets\n    FILE \${CMAKE_CURRENT_BINARY_DIR}/plutosvgTargets.cmake\n    NAMESPACE plutosvg::\n)" "" PLUTOSVG_CMAKELISTS_CONTENTS "${PLUTOSVG_CMAKELISTS_CONTENTS}")
file(WRITE "${PLUTOSVG_DIR}/CMakeLists.txt" "${PLUTOSVG_CMAKELISTS_CONTENTS}")
